apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
        - name: generator
          image: kurtaga/generator-service:v10
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONNECTIONURL
              value: jdbc:postgresql://ep-royal-river-45970815.eu-central-1.aws.neon.tech:5432/generator
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mydbsecret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mydbsecret
                  key: password

#          livenessProbe:
#            httpGet:
#              path: /health/live
#              port: 8080
#            initialDelaySeconds: 10
#            periodSeconds: 5
#          readinessProbe:
#            httpGet:
#              path: /health/ready
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 5